/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vink.mqttshield.core;

import com.hivemq.client.mqtt.MqttClient;
import com.hivemq.client.mqtt.mqtt3.Mqtt3AsyncClient;
import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    private static final UUID clientid = UUID.randomUUID();

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Mqtt3AsyncClient client = MqttClient.builder()
        .useMqttVersion3()
        .identifier(clientid.toString())
        .serverHost("localhost")
        .serverPort(1883)
        .useSslWithDefaultConfig()
        .buildAsync();
        System.out.println("Done ");

    }
}
