/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vink.mqttshield.core;

import java.util.*;

import org.eclipse.paho.client.mqttv3.MqttException;

import vink.mqttshield.routines.SysInfoExtract;
import vink.mqttshield.routines.UserPassBruteForce;

public class RoutineRunner {

    private static final UUID clientid = UUID.randomUUID();
    String topic        = "MQTT Examples";
    String content      = "Message from MqttPublishSample";
    int qos             = 0;
    static String broker       = "tcp://localhost:1883";
    static String host = "localhost";
    static int port = 1883;
    private static  boolean ifBrute = false;
    private static boolean ifSysinfo = true;
    public static void main(String[] args) {
        try {
          
          if ( ifBrute ){  
          MqttConnManager manager = new MqttConnManager(host, port);          
          UserPassBruteForce routine = new UserPassBruteForce();
          boolean success = routine.tryBruteForce(manager.getClient());
          if (success ){
            System.out.println("Matching user:pass found ");
          }
            System.out.println("Brute force attempt complete ");
          
        }

        if (ifSysinfo){
          MqttConnManager manager = new MqttConnManager(host, port , "testuser" , "password");
          SysInfoExtract routine = new SysInfoExtract();
          routine.trySysInfoTopics(manager.getClient() ,manager.getOps() );
        }
        } catch (MqttException | InterruptedException e) {
          System.out.println("Something went wrong " + e.getMessage());
        }
        

    }
}
